# ans = input("이름은? ")
# print(ans)
year = input("태어난해를 4자리로 입력")
age = 2026 - int(year)
print("당신의 나이는 ",age)
print("당신의 나이는", "만"+str(age)+"세","입니다")
print("당신은 "+year+"년에 태어났습니다")
print("당신의 나이는 ",str(age))
